# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main_win(object):
    def setupUi(self, main_win):
        main_win.setObjectName(_fromUtf8("main_win"))
        main_win.resize(500, 600)
        main_win.setMinimumSize(QtCore.QSize(500, 400))
        main_win.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(main_win)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 300))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.workspace_gb = QtGui.QGroupBox(self.centralwidget)
        self.workspace_gb.setMinimumSize(QtCore.QSize(0, 100))
        self.workspace_gb.setMaximumSize(QtCore.QSize(16777215, 100))
        self.workspace_gb.setFlat(False)
        self.workspace_gb.setObjectName(_fromUtf8("workspace_gb"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.workspace_gb)
        self.horizontalLayout_3.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_3 = QtGui.QFrame(self.workspace_gb)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.frame_3)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.header_ledit = QtGui.QLineEdit(self.frame)
        self.header_ledit.setObjectName(_fromUtf8("header_ledit"))
        self.horizontalLayout.addWidget(self.header_ledit)
        self.header_tb = QtGui.QToolButton(self.frame)
        self.header_tb.setObjectName(_fromUtf8("header_tb"))
        self.horizontalLayout.addWidget(self.header_tb)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.workspace_ledit = QtGui.QLineEdit(self.frame_2)
        self.workspace_ledit.setObjectName(_fromUtf8("workspace_ledit"))
        self.horizontalLayout_2.addWidget(self.workspace_ledit)
        self.testdata_tb = QtGui.QToolButton(self.frame_2)
        self.testdata_tb.setObjectName(_fromUtf8("testdata_tb"))
        self.horizontalLayout_2.addWidget(self.testdata_tb)
        self.verticalLayout.addWidget(self.frame_2)
        self.progressBar = QtGui.QProgressBar(self.frame_3)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.workspace_gb)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.process_btn = QtGui.QPushButton(self.frame_4)
        self.process_btn.setMinimumSize(QtCore.QSize(77, 55))
        self.process_btn.setObjectName(_fromUtf8("process_btn"))
        self.verticalLayout_2.addWidget(self.process_btn)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.workspace_gb)
        self.output_gb = QtGui.QGroupBox(self.centralwidget)
        self.output_gb.setMinimumSize(QtCore.QSize(480, 160))
        self.output_gb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_gb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.output_gb.setObjectName(_fromUtf8("output_gb"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.output_gb)
        self.horizontalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.output_te = QtGui.QTextEdit(self.output_gb)
        self.output_te.setReadOnly(True)
        self.output_te.setAcceptRichText(False)
        self.output_te.setObjectName(_fromUtf8("output_te"))
        self.horizontalLayout_5.addWidget(self.output_te)
        self.verticalLayout_3.addWidget(self.output_gb)
        self.btns_frm = QtGui.QFrame(self.centralwidget)
        self.btns_frm.setMinimumSize(QtCore.QSize(0, 50))
        self.btns_frm.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btns_frm.setFrameShape(QtGui.QFrame.StyledPanel)
        self.btns_frm.setFrameShadow(QtGui.QFrame.Raised)
        self.btns_frm.setObjectName(_fromUtf8("btns_frm"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.btns_frm)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.newProcess_btn = QtGui.QPushButton(self.btns_frm)
        self.newProcess_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.newProcess_btn.setMaximumSize(QtCore.QSize(120, 40))
        self.newProcess_btn.setObjectName(_fromUtf8("newProcess_btn"))
        self.horizontalLayout_4.addWidget(self.newProcess_btn)
        self.cancel_btn = QtGui.QPushButton(self.btns_frm)
        self.cancel_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.cancel_btn.setMaximumSize(QtCore.QSize(120, 40))
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.goAnalyze_btn = QtGui.QPushButton(self.btns_frm)
        self.goAnalyze_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.goAnalyze_btn.setMaximumSize(QtCore.QSize(120, 40))
        self.goAnalyze_btn.setObjectName(_fromUtf8("goAnalyze_btn"))
        self.horizontalLayout_4.addWidget(self.goAnalyze_btn)
        self.verticalLayout_3.addWidget(self.btns_frm)
        main_win.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        main_win.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main_win)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        main_win.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(main_win)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(main_win)
        QtCore.QMetaObject.connectSlotsByName(main_win)

    def retranslateUi(self, main_win):
        main_win.setWindowTitle(_translate("main_win", "PlotCsv [APS2600E]", None))
        self.workspace_gb.setTitle(_translate("main_win", "Current Workspace", None))
        self.header_ledit.setPlaceholderText(_translate("main_win", "Select \'Header Files\' folder", None))
        self.header_tb.setText(_translate("main_win", "...", None))
        self.workspace_ledit.setPlaceholderText(_translate("main_win", "Select \'Test Data\' folder", None))
        self.testdata_tb.setText(_translate("main_win", "...", None))
        self.process_btn.setText(_translate("main_win", "Process", None))
        self.output_gb.setTitle(_translate("main_win", "Output", None))
        self.output_te.setHtml(_translate("main_win", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.newProcess_btn.setText(_translate("main_win", "New", None))
        self.cancel_btn.setText(_translate("main_win", "Cancel", None))
        self.goAnalyze_btn.setText(_translate("main_win", "Analyze", None))
        self.menuFile.setTitle(_translate("main_win", "File", None))
        self.menuHelp.setTitle(_translate("main_win", "Help", None))
        self.actionAbout.setText(_translate("main_win", "About", None))

